GET http://localhost:3001/api/persons/670849ea5c654e457e6d2918

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Ahsan",
    "number": "123456"
}

###
DELETE http://localhost:3001/api/persons/67085258c2a85bd542cf5e89

###
PUT http://localhost:3001/api/persons/6708507338f7da1a47a36d0b
content-type: application/json

{

  "name": "Ahsan",
  "number": "1234568999"
}



