GET http://localhost:3001/api/persons/670849ea5c654e457e6d2918

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Ebraam",
    "number": "12-345678"
}

###
DELETE http://localhost:3001/api/persons/67085298c2a85bd542cf5e90

###
PUT http://localhost:3001/api/persons/67094674aa55b1bc5f1d77e7
content-type: application/json

{

  "name": "Nazm",
  "number": "123-4568999"
}



